---

- name: Ensure dotfiles repo is present
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_dir }}"
    accept_hostkey: "{{ dotfiles_accept_hostkey }}"
  become: no

- name: Ensure dotfiles are links and not files
  shell: "ls -F {{ dotfiles_home }}/{{ item }}"
  register: existing_dotfile
  failed_when: false
  always_run: yes
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles if a replacment is being linked
  file:
    path: "{{ dotfiles_home }}/{{ existing_dotfile.results }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile.results }}"

- name: Link dotfiles into {{ dotfiles_home }}
  file:
    src: "{{ dotfiles_repo_local_dir }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
  become: no
  with_items: "{{ dotfiles_files }}"

